### ISSUE TITLE
Modify the unit tests to not depend on internal-only code

### ISSUE THREAD

**Issue by DemiMarie** [microsoft/SymCrypt#17]
Currently, the unit tests depend on code that is not publicly available.  Judging by the name “msbignum”, it should be possible to replace this with an alternative bignum implementation, such as GMP, OpenSSL, or libtommath.

**Comment by samuel-lee-msft** [comment]
Hi Demi,

The unit tests should build fine without access to the internal code. You should be able to follow the instructions in the README, but skipping step 2)

If you have not yet cloned the jitterentropy-library submodule, you can get this without the internal code using:
`git submodule update --init -- jitterentropy-library`

Hope that helps. If you are still having trouble, please could you share some more details about the environment you are trying to build in, and share the output of your cmake commands?

**Comment by DemiMarie** [comment]
> Hope that helps. If you are still having trouble, please could you share some more details about the environment you are trying to build in, and share the output of your cmake commands?

This is purely a documentation question in that case, which is fine.  I thought that the tests required the submodule to be present, which seemed strange for an open source project.

**Comment by mlindgren** [comment]
@DemiMarie I'm marking this issue as closed for now, but please feel free to reopen it or reach out again if you have additional questions.
