### ISSUE TITLE
Support to build arm build

### ISSUE THREAD

**Issue by xumia** [microsoft/SymCrypt#20]
We have a lot of devices only can use armhf. Could you please support it? Thanks so much.

**Comment by mlindgren** [comment]
@samuel-lee-msft can you comment on this? I'm not familiar with the different flavors of ARM or what supporting this would entail.

**Comment by mlindgren** [comment]
ARMHF support is not currently a priority for us, but it could be something that we add in the future. I'll leave this issue open for now.
