### ISSUE TITLE
Update README for jitterentropy submodule

### ISSUE THREAD

**Issue by bkmgit** [microsoft/SymCrypt#25]
Consider updating README from
`git submodule update --init -- jitterentropy-library`
to
`git submodule update --init -- 3rdparty/jitterentropy-library`
or change linked location.

**Comment by mlindgren** [comment]
Thanks for pointing this out. We will fix it in the next release.

**Comment by mlindgren** [comment]
Sorry for the delay. We've now published our latest code to GitHub, which contains a fix for this.
