### ISSUE TITLE
Feature request: Intel Key-Locker

### ISSUE THREAD

**Issue by FredrikGCHKP** [microsoft/SymCrypt#30]
Are there any plans to support the Intel Key-Locker instructions in any way? 
https://www.intel.com/content/www/us/en/develop/download/intel-key-locker-specification.html

**Comment by mlindgren** [comment]
Hi @FredrikGCHKP, we've done some investigation of Key Locker in the past, but we determined that it's not a good fit for the kind of scenarios we envision SymCrypt being used for. As such, it's not something we have any plans to invest in.

If there's a specific use case you have in mind, we could take that into consideration, but to be transparent, it's unlikely that it would change our priorities.

Cheers,
Mitch
