### ISSUE TITLE
Providing substitue for _aligned_malloc and _aligned_free

### ISSUE THREAD

**Issue by mjsabby** [microsoft/SymCrypt#37]
Is there a reason why in the test module and the new user module that the allocation functions are not settable by the library user?

For example, it's possible a user may want to use the stack for providing memory in super high performance scenarios.

Sorry this is more of a discussion but I didn't see the discussion tab open.

**Comment by mjsabby** [comment]
I create #38 for this.

**Comment by NielsFerguson** [comment]
Thanks for looking at the code and thinking about how to improve it.

See my comment on the pull request as to why I don't see how this would be an improvement.

**Comment by mlindgren** [comment]
Copying Niels' comments from the PR:

> I don't see how this would work as there are often multiple users of the SymCrypt module in the same address space. If one caller overrides the memory allocations to get a benefit, then it will very often lead to problems when other callers in the same address space also use SymCrypt and their allocations also get re-routed. I've seen a library that had the allocation parameters on Thread-Local-Storage, but that fails if you have worker threads where the same thread does work for multiple high-level modules in the address space, and the low-level code that actually calls SymCrypt doesn't know about any of that.
> 
> SymCrypt already works hard to minimize the allocations needed. We only use allocations for asymmetric operations, which are relatively expensive already making the overhead small. We also limit ourselves to one allocation per operation; an RSA signature will do a single allocation for the whole signature operation. I don't see any significant benefit possible with making the allocations configurable.
> 
> Note that the SymCrypt static-link library does use callback functions allowing the caller to implement the memory allocation.
