### ISSUE TITLE
Test suite failures in RSA when using Cng

### ISSUE THREAD

**Issue by woachk** [microsoft/SymCrypt#5]
![image](https://user-images.githubusercontent.com/24752637/57549476-f02dca00-7363-11e9-8ec9-5065b1b94878.png)

According to the documentation, "The key size must be greater than or equal to 512 bits, less than or equal to 16384 bits, and must be a multiple of 64" from https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/nf-bcrypt-bcryptgeneratekeypair. In this case it isn't, and it makes Cng stop early.

Using 
g_BitSizeEntries[iSize].nBitsOfModulus = g_BitSizeEntries[iSize].nBitsOfModulus & ~63; makes the test suite fail much later than that point.

Any reason why?

**Comment by NielsFerguson** [comment]
What version of Windows are you running on? I don’t think we’ve ever run this test code on anything older than Windows 10 RS1; it might very well be that CNG dropped the ‘multiple of 64’ requirements at some point, and our test code just uses that.

We have a Win7 test in the repo, but that was created a long time ago and we have no regular process for running it on Win7. I’d have to run it manually, which involves setting up a Win7 VM, and then spending a day or two fixing all the bugs, and why exactly would I do that?

Cheers!

Niels

**Comment by woachk** [comment]
@NielsFerguson This is on Windows 10 version 1903 (build 18362.53/19H1)...

**Comment by NielsFerguson** [comment]
@woachk:  Strange; we've been running the full unit test (including the CNG tests) on the latest Win10 builds multiple times each day for many years. No idea what this could be.

**Comment by woachk** [comment]
@NielsFerguson does https://gist.github.com/woachk/71cb7692b2f328dc7331f21161a37283 as a minimal testcase for this run successfully for you? It'll help me a bit to pinpoint the failure.

**Comment by NielsFerguson** [comment]
I checked the Windows source code; CNG default provider limits RSA key generation to keys where the modulus is a multiple of 8 bits. We reduced that from the 64 bits it was before to provide more flexibility, but don't allow odder sizes to avoid interoperability issues we've seen.

**Comment by woachk** [comment]
Removing those sizes makes the test pass:  ![image](https://user-images.githubusercontent.com/24752637/57568213-6d008880-73e4-11e9-9d1b-e125901d0b50.png)

889 isn't a multiple of 8 either...
